# Generated by Django 3.2.16 on 2022-10-19 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('data_refresh_time', models.TimeField(blank=True, null=True)),
                ('time_zone', timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Asia/Kolkata')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('datapull_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equity',
            managers=[
                ('datapull_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equityindex',
            managers=[
                ('datapull_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='index',
            managers=[
                ('datapull_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='marketexchange',
            managers=[
                ('datapull_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='equity',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equities', to='market_lookup.exchange'),
        ),
        migrations.AlterField(
            model_name='index',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='market_lookup.exchange'),
        ),
        migrations.AlterField(
            model_name='marketdaytype',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_types', to='market_lookup.exchange'),
        ),
    ]
