# Generated by Django 3.2.16 on 2022-10-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_lookup', '0002_auto_20221019_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketExchange',
        ),
    ]
