# Generated by Django 3.2.16 on 2022-10-19 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_lookup', '0001_initial'),
        ('user_lookup', '0001_initial'),
        ('admin_lookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todofolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestrate',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rates', to='user_lookup.accounttype'),
        ),
        migrations.AddField(
            model_name='demataccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demat_account', to='user_lookup.account'),
        ),
        migrations.AddField(
            model_name='demataccount',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demat_account', to='market_lookup.marketbroker'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_record', to='user_lookup.accounttype'),
        ),
        migrations.AddField(
            model_name='accountinterestrate',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rates', to='user_lookup.account'),
        ),
        migrations.AddField(
            model_name='accountcheque',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_cheques', to='user_lookup.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='user_lookup.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='admin_lookup.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_record', to='user_lookup.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ManyToManyField(related_name='accounts', to='user_lookup.Person'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
