# Generated by Django 3.2.16 on 2022-10-27 11:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equityliveopeninterest',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='indexliveopeninterest',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='equityliveopeninterest',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexliveopeninterest',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='equitylivedata',
            unique_together={('equity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='equityliveopeninterest',
            unique_together={('equity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='indexlivedata',
            unique_together={('index', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='indexliveopeninterest',
            unique_together={('index', 'date')},
        ),
    ]
