# Generated by Django 3.2.16 on 2022-10-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DerivativeEndOfDay',
            new_name='EquityDerivativeEndOfDay',
        ),
        migrations.RenameModel(
            old_name='LiveOptionChain',
            new_name='LiveEquityOptionChain',
        ),
    ]
