# Generated by Django 3.2.16 on 2022-10-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equity',
            options={'ordering': ['created_at'], 'verbose_name': 'Equity', 'verbose_name_plural': 'Equities'},
        ),
        migrations.AlterModelOptions(
            name='equityindex',
            options={'ordering': ['-created_at'], 'verbose_name': 'Equity Index Weightage', 'verbose_name_plural': 'Equity Index Weightages'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exchange', 'verbose_name_plural': 'Exchanges'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['created_at'], 'verbose_name': 'Index', 'verbose_name_plural': 'Indices'},
        ),
        migrations.AlterModelOptions(
            name='marketbroker',
            options={'ordering': ['-created_at'], 'verbose_name': 'Market Broker', 'verbose_name_plural': 'Market Brokers'},
        ),
        migrations.AlterModelOptions(
            name='marketday',
            options={'ordering': ['-created_at'], 'verbose_name': 'Market Day', 'verbose_name_plural': 'Market Days'},
        ),
        migrations.AlterModelOptions(
            name='marketdaycategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Market Day Category', 'verbose_name_plural': 'Market Day Categories'},
        ),
        migrations.AlterModelOptions(
            name='marketdaytype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Market Day Type', 'verbose_name_plural': 'Market Day Types'},
        ),
        migrations.AlterModelOptions(
            name='marketsector',
            options={'ordering': ['-created_at'], 'verbose_name': 'Market Sector', 'verbose_name_plural': 'Market Sectors'},
        ),
        migrations.AlterModelOptions(
            name='markettradingstrategy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trading Strategy', 'verbose_name_plural': 'Trading Startegies'},
        ),
        migrations.AlterModelOptions(
            name='markettradingstrategysymbol',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trading Startegy Symbol', 'verbose_name_plural': 'Trading Strategy Symbols'},
        ),
    ]
