# Generated by Django 3.2.16 on 2022-10-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketdaycategory',
            old_name='day_type',
            new_name='daytype',
        ),
    ]
