# Generated by Django 3.2.16 on 2022-10-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_day_type_marketdaycategory_daytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketday',
            name='daytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='market.marketdaytype'),
            preserve_default=False,
        ),
    ]
