# Generated by Django 3.2.16 on 2022-10-28 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20221027_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitylivefuture',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='IndexLiveDerivativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('instrument', models.CharField(choices=[('FUTSTK', 'Futstk'), ('FUTIDX', 'Futidx'), ('OPTSTK', 'Optstk'), ('OPTIDX', 'Optidx'), ('CASH', 'Cash')], max_length=50)),
                ('contract', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('strike_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('CE', 'Ce'), ('PE', 'Pe')], max_length=50, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('point_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('percentage_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('volumn', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('change_in_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('no_of_trades', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date', models.DateTimeField()),
                ('pull_date', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivative_live_data', to='market.index')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('index', 'date', 'instrument', 'expiry_date', 'strike_price', 'option_type')},
            },
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EquityLiveDerivativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('instrument', models.CharField(choices=[('FUTSTK', 'Futstk'), ('FUTIDX', 'Futidx'), ('OPTSTK', 'Optstk'), ('OPTIDX', 'Optidx'), ('CASH', 'Cash')], max_length=50)),
                ('contract', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('strike_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('CE', 'Ce'), ('PE', 'Pe')], max_length=50, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('point_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('percentage_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('volumn', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('change_in_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('no_of_trades', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date', models.DateTimeField()),
                ('pull_date', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivative_live_data', to='market.equity')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('index', 'date', 'instrument', 'expiry_date', 'strike_price', 'option_type')},
            },
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
    ]
