# Generated by Django 3.2.16 on 2022-10-22 02:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_marketday_daytype'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equity',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equityendofday',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equityindex',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='exchange',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='index',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='indexendofday',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
    ]
