# Generated by Django 4.1.3 on 2022-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_equityendofday_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="equity",
            name="ticker_symbol",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="index",
            name="ticker_symbol",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
