# Generated by Django 3.2.16 on 2022-10-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20221028_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equityderivativeendofday',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equityendofday',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equityendofdaycalcutated',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equityinsidertrade',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equitylivedata',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equitylivefuture',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equityliveopeninterest',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equityliveoptionchain',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equitypledged',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='equitysast',
            old_name='equity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='indexderivativeendofday',
            old_name='index',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='indexendofday',
            old_name='index',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='indexlivedata',
            old_name='index',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='indexlivederivativedata',
            old_name='index',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='indexlivefuture',
            old_name='index',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='indexliveopeninterest',
            old_name='index',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='indexliveoptionchain',
            old_name='index',
            new_name='entity',
        ),
        migrations.AlterUniqueTogether(
            name='equityderivativeendofday',
            unique_together={('entity', 'date', 'instrument', 'expiry_date', 'strike_price', 'option_type')},
        ),
        migrations.AlterUniqueTogether(
            name='equityendofday',
            unique_together={('entity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='equityendofdaycalcutated',
            unique_together={('entity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='equitylivedata',
            unique_together={('entity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='equityliveopeninterest',
            unique_together={('entity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='indexderivativeendofday',
            unique_together={('entity', 'date', 'instrument', 'expiry_date', 'strike_price', 'option_type')},
        ),
        migrations.AlterUniqueTogether(
            name='indexendofday',
            unique_together={('entity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='indexlivedata',
            unique_together={('entity', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='indexlivederivativedata',
            unique_together={('entity', 'date', 'instrument', 'expiry_date', 'strike_price', 'option_type')},
        ),
        migrations.AlterUniqueTogether(
            name='indexliveopeninterest',
            unique_together={('entity', 'date')},
        ),
    ]
