# Generated by Django 3.2.16 on 2022-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20221028_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitylivederivativedata',
            name='list_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexlivederivativedata',
            name='list_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
