# Generated by Django 3.2.16 on 2022-10-22 03:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20221022_0751'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='marketday',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='marketdaycategory',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='marketdaytype',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
    ]
