# Generated by Django 3.2.16 on 2022-10-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_marketdaycategory_parent_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equityendofday',
            unique_together={('equity', 'date')},
        ),
    ]
