# Generated by Django 3.2.16 on 2022-10-23 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_equityendofday_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equityderivativeendofday',
            old_name='settle_price',
            new_name='avg_price',
        ),
        migrations.RenameField(
            model_name='equityendofday',
            old_name='turn_overs_in_lacs',
            new_name='traded_value',
        ),
        migrations.RenameField(
            model_name='indexendofday',
            old_name='turn_overs_in_cr',
            new_name='traded_value',
        ),
        migrations.RemoveField(
            model_name='equityendofday',
            name='average_delivery_percentage',
        ),
        migrations.RemoveField(
            model_name='equityendofday',
            name='average_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityendofday',
            name='average_quantity_per_trade',
        ),
        migrations.RemoveField(
            model_name='equityendofday',
            name='average_volumn',
        ),
        migrations.RemoveField(
            model_name='equityendofday',
            name='open_interest',
        ),
        migrations.RemoveField(
            model_name='equityendofday',
            name='promotor_holding_percentage',
        ),
        migrations.AddField(
            model_name='equityderivativeendofday',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equityderivativeendofday',
            name='percentage_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equityderivativeendofday',
            name='point_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equityderivativeendofday',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexendofday',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexendofday',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexendofday',
            name='number_of_trades',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexendofday',
            name='quantity_per_trade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='liveequitydata',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='liveequitydata',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='liveequitydata',
            name='equity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_data', to='market.equity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liveequityderivative',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='liveequityderivative',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='equityderivativeendofday',
            name='equity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivative_eod_data', to='market.equity'),
        ),
        migrations.AlterField(
            model_name='equityendofday',
            name='equity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_data', to='market.equity'),
        ),
        migrations.AlterField(
            model_name='equityinsidertrade',
            name='value_of_shares',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indexderivativeendofday',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivative_eod_data', to='market.index'),
        ),
        migrations.AlterField(
            model_name='indexendofday',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_data', to='market.index'),
        ),
        migrations.AlterUniqueTogether(
            name='indexendofday',
            unique_together={('index', 'date')},
        ),
        migrations.CreateModel(
            name='EquityEndOfDayCalcutated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('average_quantity_per_trade', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('average_volumn', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('average_delivery_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('average_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date', models.DateField()),
                ('pull_date', models.DateTimeField(auto_now=True)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_calculated_data', to='market.equity')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('equity', 'date')},
            },
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
    ]
