# Generated by Django 4.1.3 on 2022-12-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_marketscreener"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marketscreener",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Market Screener",
                "verbose_name_plural": "Market Screeners",
            },
        ),
        migrations.AddField(
            model_name="marketscreener",
            name="direction",
            field=models.CharField(
                choices=[("NEUTRAL", "Neutral"), ("LONG", "Long"), ("SHORT", "Short")],
                default="NEUTRAL",
                max_length=50,
            ),
        ),
    ]
