# Generated by Django 3.2.16 on 2022-10-28 13:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20221028_1818'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equitylivefuture',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equityliveoptionchain',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='indexlivefuture',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='indexliveoptionchain',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='equitylivederivativedata',
            old_name='index',
            new_name='entity',
        ),
        migrations.AlterUniqueTogether(
            name='equitylivederivativedata',
            unique_together={('entity', 'date', 'instrument', 'expiry_date', 'strike_price', 'option_type')},
        ),
    ]
