# Generated by Django 4.1.3 on 2022-12-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_marketscreener_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketScreenerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("weightage", models.IntegerField()),
                ("enabled", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_catgeories",
                        to="market.marketscreenercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Screener Category",
                "verbose_name_plural": "Market Screener Categories",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
