# Generated by Django 3.2.16 on 2022-10-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20221025_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='change_in_open_interest',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='expiry_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='instrument',
            field=models.CharField(choices=[('FUTSTK', 'Futstk'), ('FUTIDX', 'Futidx'), ('OPTSTK', 'Optstk'), ('OPTIDX', 'Optidx'), ('CASH', 'Cash')], max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='no_of_contracts',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='open_interest',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='option_type',
            field=models.CharField(blank=True, choices=[('CE', 'Ce'), ('PE', 'Pe')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='percentage_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='point_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexderivativeendofday',
            name='value_of_contracts',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='equityderivativeendofday',
            name='option_type',
            field=models.CharField(blank=True, choices=[('CE', 'Ce'), ('PE', 'Pe')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='indexderivativeendofday',
            unique_together={('index', 'date', 'instrument', 'expiry_date', 'strike_price', 'option_type')},
        ),
    ]
