# Generated by Django 4.1.3 on 2022-12-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_marketscreenercategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketscreener",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screener",
                to="market.marketscreenercategory",
            ),
        ),
    ]
