# Generated by Django 3.2.16 on 2022-10-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20221028_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityliveoptionchain',
            name='instrument',
            field=models.CharField(choices=[('FUTSTK', 'Futstk'), ('FUTIDX', 'Futidx'), ('OPTSTK', 'Optstk'), ('OPTIDX', 'Optidx'), ('CASH', 'Cash')], max_length=50),
        ),
        migrations.AddField(
            model_name='indexliveoptionchain',
            name='instrument',
            field=models.CharField(choices=[('FUTSTK', 'Futstk'), ('FUTIDX', 'Futidx'), ('OPTSTK', 'Optstk'), ('OPTIDX', 'Optidx'), ('CASH', 'Cash')], max_length=50),
        ),
    ]
