# Generated by Django 3.2.16 on 2022-10-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20221029_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityindex',
            name='last_update_date',
        ),
        migrations.AddField(
            model_name='equity',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equityindex',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='index',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
