# Generated by Django 4.1.3 on 2022-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_marketscreener_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketscreener",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="marketscreener",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="marketscreenercategory",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="marketscreenercategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
