# Generated by Django 4.1.3 on 2022-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_alter_marketscreener_code_alter_marketscreener_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketscreener",
            name="weightage",
        ),
        migrations.RemoveField(
            model_name="marketscreenercategory",
            name="weightage",
        ),
        migrations.AddField(
            model_name="marketscreener",
            name="params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
