# Generated by Django 3.2.16 on 2022-10-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20221031_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='pull_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='equityindex',
            old_name='pull_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='pull_date',
            new_name='date',
        ),
    ]
