# Generated by Django 3.2.16 on 2022-10-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20221025_1146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantactivity',
            unique_together={('client_type', 'date', 'instrument')},
        ),
        migrations.RemoveField(
            model_name='participantactivity',
            name='change_in_open_interest',
        ),
        migrations.RemoveField(
            model_name='participantactivity',
            name='no_of_contracts',
        ),
        migrations.RemoveField(
            model_name='participantactivity',
            name='open_interest',
        ),
        migrations.RemoveField(
            model_name='participantactivity',
            name='option_type',
        ),
        migrations.RemoveField(
            model_name='participantactivity',
            name='value_of_contracts',
        ),
    ]
