# Generated by Django 4.1.3 on 2022-12-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0010_remove_marketscreener_weightage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketscreener",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screener",
                to="market.marketscreenercategory",
            ),
            preserve_default=False,
        ),
    ]
