# Generated by Django 3.2.16 on 2022-10-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20221025_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantactivity',
            name='client_type',
            field=models.CharField(choices=[('FII', 'Fii'), ('DII', 'Dii'), ('PRO', 'Pro'), ('CLIENT', 'Client')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participantstatsactivity',
            name='client_type',
            field=models.CharField(choices=[('FII', 'Fii'), ('DII', 'Dii'), ('PRO', 'Pro'), ('CLIENT', 'Client')], max_length=50),
        ),
    ]
