# Generated by Django 4.1.3 on 2022-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0011_alter_marketscreener_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketscreener",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
