# Generated by Django 4.1.3 on 2022-12-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0012_alter_marketscreener_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="equityliveoptionchain",
            name="last_traded_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="equityliveoptionchain",
            name="last_traded_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indexliveoptionchain",
            name="last_traded_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="indexliveoptionchain",
            name="last_traded_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
