# Generated by Django 3.2.16 on 2022-11-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20221101_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketday',
            options={'ordering': ['date'], 'verbose_name': 'Market Day', 'verbose_name_plural': 'Market Days'},
        ),
        migrations.AddField(
            model_name='marketdaycategory',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='market.exchange'),
        ),
        migrations.AlterField(
            model_name='marketdaytype',
            name='name',
            field=models.CharField(choices=[('Trading Holidays', 'Trading Holidays'), ('Clearing Holidays', 'Clearing Holidays'), ('Weekly Off Days', 'Weekly Off Days'), ('Special Trading Days', 'Special Trading Days')], max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='marketdaycategory',
            unique_together={('exchange', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='marketdaytype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='marketdaycategory',
            name='daytype',
        ),
        migrations.RemoveField(
            model_name='marketdaytype',
            name='exchange',
        ),
    ]
