# Generated by Django 4.1.3 on 2022-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0013_equityliveoptionchain_last_traded_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketscreener",
            name="weigtage",
            field=models.IntegerField(default=3),
        ),
    ]
