# Generated by Django 3.2.16 on 2022-11-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20221101_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdaycategory',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_categories', to='market.exchange'),
        ),
    ]
