# Generated by Django 3.2.16 on 2022-10-26 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20221026_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('point_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('percentage_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('traded_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('traded_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('number_of_trades', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('quantity_per_trade', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date', models.DateTimeField()),
                ('pull_date', models.DateTimeField(auto_now=True)),
                ('year_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('year_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('near_week_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('near_week_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('price_change_month_ago', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date_month_ago', models.DateField(blank='True', null=True)),
                ('price_change_year_ago', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date_year_ago', models.DateField(blank='True', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityLiveFuture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('point_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('percentage_changed', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('expiry_date', models.DateField()),
                ('date', models.DateTimeField()),
                ('pull_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityLiveOpenInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastest_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('previous_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('change_in_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('average_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('volume_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('future_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('option_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('underlying_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date', models.DateTimeField()),
                ('pull_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityLiveOptionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pe_strike_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_expiry_date', models.DateField()),
                ('pe_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_change_in_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_total_traded_volume', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_implied_volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_last_traded_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_change', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_total_buy_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_total_sell_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_bid_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_bid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_ask_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_ask_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pe_underlying_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_strike_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_expiry_date', models.DateField()),
                ('ce_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_change_in_open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_total_traded_volume', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_implied_volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_last_traded_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_change', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_total_buy_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_total_sell_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_bid_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_bid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_ask_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_ask_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ce_underlying_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('date', models.DateTimeField()),
                ('pull_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LiveIndexData',
        ),
        migrations.DeleteModel(
            name='LiveIndexDerivative',
        ),
        migrations.DeleteModel(
            name='LiveIndexOptionChain',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='date_month_ago',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='date_year_ago',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='near_week_high',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='near_week_low',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='number_of_trades',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='percentage_changed',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='point_changed',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='prev_close',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='price_change_month_ago',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='price_change_year_ago',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='pull_date',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='quantity_per_trade',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='traded_quantity',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='traded_value',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='year_high',
        ),
        migrations.RemoveField(
            model_name='equitylivedata',
            name='year_low',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='percentage_changed',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='point_changed',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='prev_close',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='pull_date',
        ),
        migrations.RemoveField(
            model_name='equitylivefuture',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='average_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='change_in_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='future_value',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='lastest_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='option_value',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='previous_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='pull_date',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='underlying_value',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='equityliveopeninterest',
            name='volume_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_ask_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_ask_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_bid_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_bid_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_change',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_change_in_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_expiry_date',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_implied_volatility',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_last_traded_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_strike_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_total_buy_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_total_sell_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_total_traded_volume',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='ce_underlying_value',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='date',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_ask_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_ask_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_bid_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_bid_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_change',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_change_in_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_expiry_date',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_implied_volatility',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_last_traded_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_open_interest',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_strike_price',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_total_buy_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_total_sell_quantity',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_total_traded_volume',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pe_underlying_value',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='pull_date',
        ),
        migrations.RemoveField(
            model_name='equityliveoptionchain',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='entitylivedata_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entitylivedata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='entitylivefuture_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entitylivefuture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equityliveopeninterest',
            name='entityliveopeninterest_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entityliveopeninterest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equityliveoptionchain',
            name='entityliveoptionchain_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entityliveoptionchain'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IndexLiveOptionChain',
            fields=[
                ('entityliveoptionchain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entityliveoptionchain')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_optionchain', to='market.index')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('market.entityliveoptionchain',),
        ),
        migrations.CreateModel(
            name='IndexLiveOpenInterest',
            fields=[
                ('entityliveopeninterest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entityliveopeninterest')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_openInterest', to='market.index')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('market.entityliveopeninterest',),
        ),
        migrations.CreateModel(
            name='IndexLiveFuture',
            fields=[
                ('entitylivefuture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entitylivefuture')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_future', to='market.index')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('market.entitylivefuture',),
        ),
        migrations.CreateModel(
            name='IndexLiveData',
            fields=[
                ('entitylivedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.entitylivedata')),
                ('one_week_ago', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('one_month_ago', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('declines', models.IntegerField(blank=True, null=True)),
                ('advances', models.IntegerField(blank=True, null=True)),
                ('unchanged', models.IntegerField(blank=True, null=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_data', to='market.index')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('market.entitylivedata',),
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
    ]
