# Generated by Django 3.2.16 on 2022-10-26 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20221026_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityliveopeninterest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entityliveoptionchain',
            options={},
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='number_of_trades',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='percentage_changed',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='point_changed',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='prev_close',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='pull_date',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='quantity_per_trade',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='traded_quantity',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='traded_value',
        ),
        migrations.RemoveField(
            model_name='entitylivedata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='percentage_changed',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='point_changed',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='prev_close',
        ),
        migrations.RemoveField(
            model_name='entitylivefuture',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='entityliveopeninterest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entityliveopeninterest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='entityliveoptionchain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entityliveoptionchain',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='number_of_trades',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='percentage_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='point_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='quantity_per_trade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='traded_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='traded_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='percentage_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='point_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='equitylivefuture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equityliveopeninterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='equityliveopeninterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equityliveoptionchain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='equityliveoptionchain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='number_of_trades',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='percentage_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='point_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='pull_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='quantity_per_trade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='traded_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='traded_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='percentage_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='point_changed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indexlivefuture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indexliveopeninterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='indexliveopeninterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='indexliveoptionchain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='indexliveoptionchain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
