# Generated by Django 3.2.16 on 2022-10-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_lookup', '0001_initial'),
        ('user_account', '0001_initial'),
        ('user_lookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_lookup.account'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='account_cheque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_lookup.accountcheque'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='todo_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_lookup.todotask'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_lookup.transactiontype'),
        ),
        migrations.AddField(
            model_name='accountstrategies',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='user_lookup.account'),
        ),
        migrations.AddField(
            model_name='accountstrategies',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_strategies', to='market_lookup.markettradingstrategy'),
        ),
        migrations.AddField(
            model_name='accountsession',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user_lookup.account'),
        ),
    ]
