# Generated by Django 3.2.16 on 2022-10-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_lookup', '0002_auto_20221019_1546'),
        ('user_account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategytrade',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_lookup.exchange'),
        ),
    ]
