# Generated by Django 4.1.3 on 2022-12-03 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0012_alter_marketscreener_description"),
        ("users", "0003_stockscreener_stockscreenersection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockWatchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("date", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "screener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.equity"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
