# Generated by Django 4.1.3 on 2022-12-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_stockwatchlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockwatchlist",
            old_name="screener",
            new_name="equity",
        ),
    ]
