# Generated by Django 4.1.3 on 2022-12-11 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0015_marketscreener_rank"),
        ("users", "0005_rename_screener_stockwatchlist_equity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockscreenersectionitem",
            name="level",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="stockscreenersectionitem",
            name="screener_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.marketscreenercategory",
            ),
        ),
        migrations.AlterField(
            model_name="stockscreenersection",
            name="weightage",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="stockscreenersectionitem",
            name="screener",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.marketscreener",
            ),
        ),
        migrations.AlterField(
            model_name="stockscreenersectionitem",
            name="weightage",
            field=models.IntegerField(default=3),
        ),
    ]
