# Generated by Django 4.1.3 on 2022-12-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_stockwatchlist_equity_stockwatchlistitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockscreenersectionitem",
            old_name="screener",
            new_name="market_screener",
        ),
        migrations.RenameField(
            model_name="stockscreenersectionitem",
            old_name="screener_category",
            new_name="market_screener_category",
        ),
        migrations.AddField(
            model_name="stockscreenersection",
            name="stock_screener",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.stockscreener",
            ),
        ),
    ]
