# Generated by Django 4.1.3 on 2022-12-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_stockscreenersectionitem_section"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockscreenersectionitem",
            old_name="market_screener",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="stockscreenersectionitem",
            old_name="market_screener_category",
            new_name="item_category",
        ),
    ]
