# Generated by Django 4.1.3 on 2022-12-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_market_screener_stockscreenersectionitem_item_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockscreenersection",
            old_name="stock_screener",
            new_name="screener",
        ),
    ]
