# Generated by Django 4.1.3 on 2022-12-11 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0015_marketscreener_rank"),
        ("users", "0011_rename_stock_screener_stockscreenersection_screener"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockwatchlistitem",
            name="index",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.index",
            ),
        ),
        migrations.AlterField(
            model_name="stockwatchlistitem",
            name="equity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.equity",
            ),
        ),
    ]
