# Generated by Django 4.1.3 on 2022-12-11 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_stockwatchlistitem_index_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="stockscreener",
            managers=[
                ("backend", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="stockscreenersection",
            managers=[
                ("backend", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="stockscreenersectionitem",
            managers=[
                ("backend", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="stockwatchlist",
            managers=[
                ("backend", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="stockwatchlistitem",
            managers=[
                ("backend", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="stockscreenersection",
            name="screener",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="users.stockscreener",
            ),
        ),
        migrations.AlterField(
            model_name="stockscreenersectionitem",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="users.stockscreenersection",
            ),
        ),
        migrations.AlterField(
            model_name="stockwatchlistitem",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="users.stockwatchlist",
            ),
        ),
    ]
