# Generated by Django 4.1.3 on 2022-12-17 05:26

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="demataccount",
            name="access_token",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=500, null=True)
            ),
        ),
        migrations.AddField(
            model_name="demataccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("API", "Api"),
                    ("DEMAT", "Demat"),
                    ("PUBLISHER", "Publisher"),
                    ("INFOMATIONAL", "Infomational"),
                    ("VIRTUAL", "Virtual"),
                ],
                default="DEMAT",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="demataccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="demataccount",
            name="is_login_initated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="demataccount",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demataccount",
            name="app_key",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=500, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="demataccount",
            name="app_secret",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=500, null=True)
            ),
        ),
    ]
