# Generated by Django 3.2.16 on 2022-10-22 02:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='setting',
            managers=[
                ('backend', django.db.models.manager.Manager()),
            ],
        ),
    ]
