# Generated by Django 3.2.16 on 2022-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(choices=[('NO_OF_DAYS_AVG', 'No Of Days Avg'), ('DATAPULL_EQUITY_LOOKUP_DATE', 'Datapull Equity Lookup Date'), ('DATAPULL_EQUITY_LOOKUP_PAUSE_HOURS', 'Datapull Equity Lookup Pause Hours'), ('DATAPULL_HOLIDAYS_LOOKUP_DATE', 'Datapull Holidays Lookup Date'), ('DATAPULL_HOLIDAYS_LOOKUP_PAUSE_HOURS', 'Datapull Holidays Lookup Pause Hours'), ('DATAPULL_EQUITY_EOD_DATA_DATE', 'Datapull Equity Eod Data Date'), ('DATAPULL_INDICES_EOD_DATA_DATE', 'Datapull Indices Eod Data Date'), ('DATAPULL_EOD_DATA_PAUSE_HOURS', 'Datapull Eod Data Pause Hours'), ('LOOKUP_DATA_OLDER_THAN_DAYS_CAN_BE_DELETED', 'Lookup Data Older Than Days Can Be Deleted')], max_length=50, unique=True),
        ),
    ]
