# Generated by Django 3.2.16 on 2022-11-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_alter_setting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
