# Generated by Django 4.1.3 on 2022-12-05 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("lookup", "0007_alter_setting_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task_id", models.CharField(blank=True, max_length=100, null=True)),
                ("task_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            managers=[
                ("backend", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="lookup.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            managers=[
                ("backend", django.db.models.manager.Manager()),
            ],
        ),
    ]
