# Generated by Django 4.1.3 on 2022-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookup", "0008_task_tasklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="processed_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="total_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
