# Generated by Django 4.1.3 on 2022-12-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookup", "0009_task_processed_count_task_status_task_total_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="key",
            field=models.CharField(
                choices=[
                    ("NO_OF_DAYS_AVG", "No Of Days Avg"),
                    (
                        "DATAPULL_EQUITY_LOOKUP_PAUSE_HOURS",
                        "Datapull Equity Lookup Pause Hours",
                    ),
                    (
                        "DATAPULL_HOLIDAYS_LOOKUP_PAUSE_HOURS",
                        "Datapull Holidays Lookup Pause Hours",
                    ),
                    ("DATAPULL_EOD_DATA_PAUSE_HOURS", "Datapull Eod Data Pause Hours"),
                    (
                        "LOOKUP_DATA_OLDER_THAN_DAYS_CAN_BE_DELETED",
                        "Lookup Data Older Than Days Can Be Deleted",
                    ),
                    (
                        "LIVE_DATA_OLDER_THAN_DAYS_CAN_BE_DELETED",
                        "Live Data Older Than Days Can Be Deleted",
                    ),
                    (
                        "DEFAULT_START_DATE_EQUITY_DATA_PULL",
                        "Default Start Date Equity Data Pull",
                    ),
                    (
                        "DEFAULT_START_DATE_INDEX_DATA_PULL",
                        "Default Start Date Index Data Pull",
                    ),
                    (
                        "DEFAULT_START_DATE_PARTICIPANT_DATA_PULL",
                        "Default Start Date Participant Data Pull",
                    ),
                    (
                        "DATAPULL_EQUITY_LOOKUP_LAST_PULL_DATE",
                        "Datapull Equity Lookup Last Pull Date",
                    ),
                    (
                        "DATAPULL_HOLIDAYS_LOOKUP_LAST_PULL_DATE",
                        "Datapull Holidays Lookup Last Pull Date",
                    ),
                    (
                        "DATAPULL_EQUITY_EOD_LAST_PULL_DATE",
                        "Datapull Equity Eod Last Pull Date",
                    ),
                    (
                        "DATAPULL_INDICES_EOD_LAST_PULL_DATE",
                        "Datapull Indices Eod Last Pull Date",
                    ),
                    (
                        "DATAPULL_PARTICIPANT_EOD_LAST_PULL_DATE",
                        "Datapull Participant Eod Last Pull Date",
                    ),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
