# Generated by Django 3.2.16 on 2022-10-19 10:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('market_equity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equityendofday',
            managers=[
                ('datapull_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
