name: Delete old workflow runs (Scheduled)
on:
  schedule:
    # Run monthly, at 00:00 on the 1st day of month.
    - cron: '0 0 1 * *'

    # Rund every day at 5:30 and 17:30 UTC
    - cron:  '30 5,17 * * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 2
